name: .NET App Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache NuGet packages and .NET tools - placed BEFORE .NET installation
    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        # Cache NuGet packages and the .NET tools
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
          ~/.dotnet/tools
        # The cache key depends on the hash of all project files and the dotnet version
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}-${{ hashFiles('**/packages.lock.json') }}
        # Restore keys in case of a cache miss
        restore-keys: |
          ${{ runner.os }}-nuget-
        # Enable cross-platform cache sharing
        enableCrossOsArchive: true
        # Don't fail if cache is missing
        fail-on-cache-miss: false
        # Always save the cache, even on workflow failure
        save-always: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Get the commit hash and create a proper version
    - name: Create version
      id: version
      run: |
        $commitHash = git rev-parse --short HEAD
        # Generate a version that conforms to SemVer format (1.0.0+[hash])
        $version = "1.0.0+$commitHash"
        $fileVersion = "1.0.0.$([int]::Parse($commitHash.Substring(0, 4), [System.Globalization.NumberStyles]::HexNumber))"
        
        echo "HASH=$commitHash" >> $env:GITHUB_OUTPUT
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "FILE_VERSION=$fileVersion" >> $env:GITHUB_OUTPUT
      shell: pwsh

    # Restore dependencies
    - name: Restore dependencies
      run: |
        $projectFile = Get-ChildItem -Path . -Filter *.csproj -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
        echo "Using project file: $projectFile"
        dotnet restore "$projectFile"
      shell: pwsh

    # Build the solution
    - name: Build
      run: |
        $solutionFile = Get-ChildItem -Path . -Filter *.sln -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
        echo "Building solution: $solutionFile"
        dotnet build "$solutionFile" --configuration Release --no-restore
      shell: pwsh

    # Run VSTest unit tests
    - name: Run unit tests
      run: |
        $testProjects = Get-ChildItem -Path . -Recurse -Filter "*Test*.csproj" | Select-Object -ExpandProperty FullName
        if ($testProjects) {
          foreach ($testProject in $testProjects) {
            echo "Running tests for: $testProject"
            dotnet test "$testProject" --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
          }
        } else {
          echo "No test projects found"
        }
      shell: pwsh

    # Publish test results
    - name: Publish test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: "**/*.trx"
        retention-days: 30

    # Publish the application with proper version
    - name: Publish
      run: |
        $projectFile = Get-ChildItem -Path . -Filter *.csproj -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
        echo "Using project file: $projectFile"
        dotnet publish "$projectFile" -p:PublishProfile=FolderProfile -p:InformationalVersion="${{ steps.version.outputs.VERSION }}" -p:AssemblyVersion="1.0.0.0" -p:FileVersion="${{ steps.version.outputs.FILE_VERSION }}"
      shell: pwsh

    # Find the published exe
    - name: Find published EXE
      id: find_exe
      run: |
        $exePath = Get-ChildItem -Path . -Filter *.exe -Recurse -File | Where-Object { $_.DirectoryName -like "*\bin\*\*\publish*" } | Select-Object -First 1 -ExpandProperty FullName
        if ($exePath) {
          echo "Found EXE at: $exePath"
          echo "EXE_PATH=$exePath" >> $env:GITHUB_OUTPUT
        } else {
          echo "No EXE found in publish directories"
          exit 1
        }
      shell: pwsh

    # Upload the EXE as an artifact
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: RTXLauncher-${{ steps.version.outputs.HASH }}
        path: ${{ steps.find_exe.outputs.EXE_PATH }}
        retention-days: 30
