name: .NET App Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Get the commit hash
    - name: Get commit hash
      id: commit_hash
      run: |
        echo "HASH=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
      shell: pwsh

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore RTXLauncher.sln

    # Publish the application with commit hash as version
    - name: Publish
      run: |
        dotnet publish RTXLauncher.csproj -p:PublishProfile=FolderProfile -p:Version=${{ steps.commit_hash.outputs.HASH }} -p:AssemblyVersion=1.0.0.${{ steps.commit_hash.outputs.HASH }} -p:FileVersion=1.0.0.${{ steps.commit_hash.outputs.HASH }}

    # Find the published exe
    - name: Find published EXE
      id: find_exe
      run: |
        $exePath = Get-ChildItem -Path . -Filter *.exe -Recurse -File | Where-Object { $_.DirectoryName -like "*\bin\*\*\publish*" } | Select-Object -First 1 -ExpandProperty FullName
        echo "EXE_PATH=$exePath" >> $env:GITHUB_OUTPUT
      shell: pwsh

    # Upload the EXE as an artifact
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: RTXLauncher-${{ steps.commit_hash.outputs.HASH }}
        path: ${{ steps.find_exe.outputs.EXE_PATH }}
        retention-days: 30
